# For ReadTheDocs

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

#sphinx:
#   configuration: docs/source/conf.py
#   builder: html

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

formats:
  - pdf

python:
   install:
   - requirements: docs/requirements.txt
